# Basic setup
title:               "Dana Johnson"
subtitle:            ""
description:         ""
url:                 http://127.0.0.1:4000
baseurl:             ""

# About/contact
author:
  name:              Dana Johnson
  url:               http://danajohnson.co
  email:             dana@danajohnson.co

# Permalinks
permalink:           pretty

# Collections
collections:

# Front Matter Defaults
defaults:
  # Posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: default

# Custom vars
version:             0.0.1

# Jekyll configuration
markdown: kramdown
keep_files:
  - .git
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - bower.json
  - s3_website.yml
gems:
  - jekyll-assets

# Plugin: Jekyll Assets
assets:
  prefix: "/assets"
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  assets:
    - "*.png"
    - "bundle.css"
