# Basic setup
title:               "Dana Johnson"
subtitle:            ""
description:         "Designing and building for pages and screens. Creating interfaces that make it a pleasure to read and research. Experimenting with minimal, sustainable tools for creating and sharing knowledge on the open web."
url:                 http://danajohnson.co
baseurl:             ""

# Third party
repository:          https://github.com/dananjohnson/dana-v2
microblog:           dana
typekit:             hhy2otg

# About/contact
author:
  name:              Dana Johnson
  url:               http://danajohnson.co
  email:             dana@danajohnson.co
license:
  title:             CC-BY 4.0
  url:               https://creativecommons.org/licenses/by/4.0/

# Permalinks
permalink:           pretty

# Collections
collections:
  projects:
    output:          true
    permalink:       /projects/:path/
    title:           "Projects"

# Front Matter Defaults
defaults:
  # Posts
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
  # Projects
  - scope:
      path: _projects
      type: projects
    values:
      layout: project

# Custom vars
version:             1.0.0

# Jekyll configuration
markdown: kramdown
keep_files:
  - .git
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - bower.json
  - s3_website.yml
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

# Plugin: Jekyll Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Plugin: Jekyll Assets
# assets:
